[package]
name = "vader"
version = "0.1.0"
authors = ["Mark Volkov <markvolkov@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
crossbeam-utils = "0.8"
scoped_threadpool = "0.1.9"